### ISSUE TITLE
Further notebook examples

### ISSUE THREAD

**Issue by michaelmior** [SpencerPark/ijava-binder#1]
Thanks a lot for IJava! I'm one of the developers on the [Apache Calcite](https://calcite.apache.org) project, which basically gives you the top half of a database without the storage (query parsing, optimization, etc.) We get a lot of questions about how to make use of Calcite and I started throwing together some basic examples and I was pleasantly surprised with how well IJava works. If you're interested in including a link, [here's the repository](http://github.com/michaelmior/calcite-notebooks).

One of the things we're considering doing is finding a good way to integrate notebook output into documentation so we can have examples that are actually verified to still be working :) It's just an idea at this point, but if you have any thoughts on how to go about it, I'd be happy to hear them.

**Comment by SpencerPark** [comment]
Hi @michaelmior, my pleasure! The Calcite project looks really cool and I'm glad IJava can help with your documentation. I am more than happy to include a link, the more the merrier :) Feel free to edit that table to add a blurb about the project or similar, you're the first so any changes to that list's format are welcome!

Options for including output depend on what you are using to build the documentation which looks like jekyll? There is the extension https://github.com/red-data-tools/jekyll-jupyter-notebook for embedding a notebook. Also `nbconvert` will run all the cells and exit with an error if a cell fails and export to html, markdown, etc. It's also not too bad to create your own template if the formats don't work for your setup.

**Comment by michaelmior** [comment]
Thanks for the link! I appreciate the pointer to the Jekyll extension. I'll take a look at that more closely :)
