### ISSUE TITLE
Notebook examples for VAVR java sample code

### ISSUE THREAD

**Issue by inspire99** [SpencerPark/ijava-binder#2]
Hi SpencerPark, Thanks a lot for IJava and Thanks a ton for Dockerfile for hosting java kernel in binder.

This is my repository which uses IJava and IJava binder to launch binder 
https://github.com/inspire99/vavr-notebook

You can add to your list of example github projects which uses IJava Binder. Thanks a ton again.

**Comment by SpencerPark** [comment]
Hey @inspire99, glad you are getting some use out of the kernel! I can't seem to find the repo you have linked, has it moved?

**Comment by SpencerPark** [comment]
Closing this as I can't find the linked repo but we can reopen if it becomes available again. Thanks!

**Comment by inspire99** [comment]
@SpencerPark , could you check now? Thanks.

**Comment by SpencerPark** [comment]
@inspire99, yep I can see it now and it looks great! 

A current combination of jupyter dependencies causes the binder to build a setup that can't connect to kernels. I've updated the Dockerfile and added a requirements.txt in this repo to get a consistent version. 

Do you mind taking a copy of both the `Dockerfile` and `requirements.txt` from here and add it to your repo? This should make the build less volatile and more consistent. Then I would be happy to add a link in the README. Thanks!

**Comment by gansai** [comment]
@SpencerPark 👍 , changes made, and its working fine.

**Comment by SpencerPark** [comment]
Great, thanks! Added it to the list!
