### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [SpencerPark/ijava-binder#3]
Could you please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

I see you've already specified the MIT license for https://github.com/SpencerPark/IJava so maybe the same license would work here?

Thanks for your work on this!

---

FWIW, per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

**Comment by SpencerPark** [comment]
Ah yes, thank you for catching that. I went for the Unlicense as that is looking like the most free choice. I want it to encourage anyone to take anything from here and I hope that license reflects that.
