### ISSUE TITLE
Other notebook examples

### ISSUE THREAD

**Issue by padreati** [SpencerPark/ijava-binder#5]
Hi SpencerPark,

When I the code on ML and statistics that I collected in my project, I was expecting to happen two things: jshell and a true jupyter java notebook. Now both of them happened  and I am very grateful for your effort and your work. Really really nice job and beautiful result.
I started to migrate the documentation of my project and examples for it on notebooks. It is a continuous work in progress, but the links will remain.

My project: https://github.com/padreati/rapaio
My binder notebooks project: https://github.com/padreati/rapaio-notebooks
I wonder if you can add the links to the ones you already have.

Again, all my gratitude for what you do!

**Comment by SpencerPark** [comment]
Hi @padreati, thanks for the kind words. I write open source software with the hope that people can find it useful and make cool things with it so I am always really happy to see whats being done and collecting some of it here!

The rapaio notebooks are awesome, thanks for making and sharing them! I've added them to the README with the badges from your notebook repo. I'd like to keep the list of links to the binder repos but encourage you to link to the upstream project in your notebook repo. If you ever want to change the badges feel free to open a PR or issue or even tag me in another comment here. 

Thanks again!
